#!/bin/bash

log() {
	local color_on=$'\e[0;32m'
	local color_off=$'\e[0m'
	echo "${color_on}[$(date)]${color_off} $@" >&2
}

log "Insert key"

log "Setting up..."
pacman -Sy &&
pacman -S libfido2 &&
eval $(ssh-agent -s) &&
ssh-add -K
log "SSH key is set up!"

log "Pulling installer"
cd ~/ &&
git clone git@github.com:0x1F680/FAISAL.git

log "Starting installer script"
cd ~/FAISAL &&
./deploy
